### ISSUE TITLE
how to get the attention score of genes

### ISSUE THREAD

**Issue by zeo46** [GSanShui/SynergyX#4]
hello, your attention map is 165*165, how it map to each gene,I think drug to cell's gene map is 165*4079.
thanks.

**Comment by GSanShui** [comment]
Apologies for the delayed response. Due to device limitations, we are unable to capture the attention scores for each individual gene token. Instead, we performed pooling in the CNN module to aggregate the information from the 4079 genes into 165 dimensions in a position-aware manner. Specifically, we linearly mapped the attention scores of size 165 to the 4079 genes.

You can refer to the following code:
```
def map_to_higher_dimension(data, target_dim=4079):
    original_dim = len(data)
    indices = np.arange(original_dim)
    target_indices = np.linspace(0, original_dim - 1, target_dim)
    mapped_data = np.interp(target_indices, indices, data)
    index_map = target_indices.astype(int)
    return mapped_data, index_map
```
